{
    'name': 'CSR and Sustainability',
    'summary': 'CSR and Sustainability Management',
    'version': '19.0.0.0.0',
    'category': 'Sustainability',
    'author': 'Workshop',
    'license': 'LGPL-3',
    'website': 'https://example.com',
    'depends': ['base', 'hr', 'project', 'portal', 'website'],
    'data': [
        'security/csr_security_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/menu.xml',
        'views/ngo_views.xml',
        'views/project_search.xml',
        'views/task_search.xml',
        'views/join_project_wizard_views.xml',
        'views/project_views.xml',
        'views/task_views.xml',
        'views/employee_views.xml',
        'views/portal_project_templates.xml',
        'data/project_data.xml',
    ],
    'application': True,
}
